jobs:
  verify-staged-with-samples:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Start RabbitMQ
      uses: namoshek/rabbitmq-github-action@v1
      with:
        plugins: rabbitmq_stream,rabbitmq_management
        ports: 5672:5672 15672:15672 5552:5552
    - continue-on-error: true
      name: Checkout Samples Repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
        repository: spring-projects/spring-amqp-samples
        show-progress: false
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      uses: jfrog/setup-jfrog-cli@v4
    - continue-on-error: true
      name: Configure JFrog Cli
      run: jf mvnc --repo-resolve-releases=libs-release-staging --repo-resolve-snapshots=snapshot
    - continue-on-error: true
      name: Verify samples against staged release
      run: 'mvn versions:set -DnewVersion=${{ inputs.releaseVersion }} -DgenerateBackupPoms=false
        -DprocessAllModules=true -B -ntp

        jf mvn verify -B -ntp

        '
    - continue-on-error: true
      if: failure()
      name: Capture Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/target/surefire-reports/**/*.*'
        retention-days: 1
name: Verify Staged Artifacts
on:
  repository_dispatch:
    types: trigger-ga___verify-staged-artifacts.yml
